spring.application.name=judgify-worker

spring.datasource.url=jdbc:mysql://localhost:3306/judgify
spring.datasource.username=judgify
spring.datasource.password=judgify
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=false
